### ISSUE TITLE
Having trouble installing the latest revision

### ISSUE THREAD

**Issue by bugssbunnyy** [levnach/z3#103]
Hi, 
I am having trouble installing the latest revision. I was having no trouble installing it before. 

During the installation, at step :
`python scripts/mk_make.py --prefix=/home/bunny/Pictures/z3LevnachBuild`

I get:

```
Generated python bytecode
Copied 'z3types.py'
Copied '__init__.py'
Copied 'z3util.py'
Copied 'z3.py'
Copied 'z3printer.py'
Copied 'z3core.py'
Copied 'z3rcf.py'
Copied 'z3num.py'
Copied 'z3consts.py'
Copied 'z3poly.py'
Copied 'z3printer.pyc'
Copied '__init__.pyc'
Copied 'z3util.pyc'
Copied 'z3rcf.pyc'
Copied 'z3num.pyc'
Copied 'z3core.pyc'
Copied 'z3types.pyc'
Copied 'z3poly.pyc'
Copied 'z3consts.pyc'
Copied 'z3.pyc'
Testing ar...
Testing g++...
Testing gcc...
Testing floating point support...
Host platform:  Linux
C++ Compiler:   g++
C Compiler  :   gcc
Archive Tool:   ar
Arithmetic:     internal
Prefix:         /home/bunny/Pictures/z3LevnachBuild
64-bit:         True
FP math:        SSE2-GCC
Python pkg dir: /usr/lib/python2.7/dist-packages
Python version: 2.7
Writing build/Makefile
Traceback (most recent call last):
  File "scripts/mk_make.py", line 21, in <module>
    mk_makefile()
  File "/home/bunny/Pictures/z3-levnach/scripts/mk_util.py", line 2724, in mk_makefile
    c.mk_makefile(out)
  File "/home/bunny/Pictures/z3-levnach/scripts/mk_util.py", line 1116, in mk_makefile
    Component.mk_makefile(self, out)
  File "/home/bunny/Pictures/z3-levnach/scripts/mk_util.py", line 1063, in mk_makefile
    self.add_cpp_rules(out, include_defs, cppfile)
  File "/home/bunny/Pictures/z3-levnach/scripts/mk_util.py", line 1020, in add_cpp_rules
    self.add_rule_for_each_include(out, cppfile)
  File "/home/bunny/Pictures/z3-levnach/scripts/mk_util.py", line 1000, in add_rule_for_each_include
    owner.add_h_rule(out, include)
  File "/home/bunny/Pictures/z3-levnach/scripts/mk_util.py", line 1012, in add_h_rule
    self.add_rule_for_each_include(out, include)
  File "/home/bunny/Pictures/z3-levnach/scripts/mk_util.py", line 999, in add_rule_for_each_include
    owner = self.find_file(include, fullname)
  File "/home/bunny/Pictures/z3-levnach/scripts/mk_util.py", line 983, in find_file
    raise MKException("Failed to find include file '%s' for '%s' when processing '%s'." % (fname, ownerfile, self.name))
mk_exception.MKException: u"Failed to find include file 'pdd_grobner.h' for 'src/math/lp/nla_core.h' when processing 'lp'."

```

**Comment by levnach** [comment]
Are you building or installing?
The error is strange: because file 'pdd_grobner.h' is on github unde https://github.com/levnach/z3/tree/master/src/math/grobner/. 
I am not sure how to reproduce the error since the content of  /home/bunny/Pictures/z3LevnachBuild is not given.

**Comment by bugssbunnyy** [comment]
I am sorry i meant building. 
At this point in the building step "/home/bunny/Pictures/z3LevnachBuild" is empty and It should be empty, no?

So far, i was just following the steps in the [readme](https://github.com/levnach/z3#building-z3-using-make-and-gccclang). Which worked fine for me. This only started to happen from today.
Maybe I can try to build some previous revision.

**Comment by bugssbunnyy** [comment]
https://github.com/levnach/z3/commit/33eecb25f854ab511d08d07be8d3f770783e5626 Is the last commit that builds without any problems

On https://github.com/levnach/z3/commit/ddaf243b68e2a29a5494269070a23fc55f6d7651 I get:
```
raise MKException("Failed to find include file '%s' for '%s' when processing '%s'." % (fname, ownerfile, self.name))
mk_exception.MKException: u"Failed to find include file 'dep_intervals.h' for 'src/math/dd/pdd_interval.h' when processing 'dd'." 
```

and from https://github.com/levnach/z3/commit/0abded82a62a26c68588a3f65e3e507a014bcd32 I start to get:

```
raise MKException("Failed to find include file '%s' for '%s' when processing '%s'." % (fname, ownerfile, self.name)
mk_exception.MKException: u"Failed to find include file 'pdd_grobner.h' for 'src/math/lp/nla_core.cpp' when processing 'lp'."
```
And this is after the first build step:
`python scripts/mk_make.py --prefix=/home/bunny/Pictures/z3LevnachBuild`

**Comment by levnach** [comment]
I fixed it with the last commit. Thanks!
